# Generated by Django 4.1.6 on 2023-03-12 18:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('PROFILES', '0002_profile_sessionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sessionId',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
