# Generated by Django 4.1.6 on 2023-03-14 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PROFILES', '0003_alter_profile_sessionid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='guc_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='xp',
        ),
    ]
