# Generated by Django 4.1.6 on 2023-03-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROFILES', '0004_remove_profile_guc_id_remove_profile_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='guc_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
