# Generated by Django 3.2.6 on 2023-02-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0002_auto_20230206_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='owner_committee',
        ),
        migrations.AddField(
            model_name='resource',
            name='committee',
            field=models.CharField(choices=[('GDD', 'GDD'), ('GSD', 'GSD'), ('GAD', 'GAD')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Committee',
        ),
    ]
