# Generated by Django 3.2.6 on 2023-02-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0003_auto_20230206_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('IMAGE', 'IMAGE'), ('VIDEO', 'VIDEO'), ('OTHER', 'OTHER')], max_length=200, null=True),
        ),
    ]
